### ISSUE TITLE
Triggers with backslashes

### ISSUE THREAD

**Issue by haoming-li-ling** [altermo/ultimate-autopair.nvim#37]
I would like to add a pair `\( \)` for tex. However, `{ "\\(", "\\)", ft = { "tex" } },` does not work. Inputting `\(` does nothing; but inputting `\\(` produces `\\(\)`. Why is this happening?

**Comment by altermo** [comment]
It is because ext.escape treats multi-character pairs as a single character, this issue will be solved in the next release.
Until then, you can disable escape with `{ "\\(", "\\)", ft = { "tex" } , noescape = true }`

**Comment by haoming-li-ling** [comment]
Thank you, that works!
However, I have another question. Now, when the pair is in place, and the cursor is at `|`, i.e., `\(|\)`, pressing `\` will bring me out of the pair. I want to disable this behavior, as in latex, it is often the case that I will input a command that starts with `\`. How can I do that?

**Comment by altermo** [comment]
Ok, fixed, and the feature added in v0.6.0 (for more info read the [Q&A](https://github.com/altermo/ultimate-autopair.nvim/blob/v0.6/Q%26A.md#how-to-disable-hop-over-end-pair))
(Note: To update to v0.6.0, remove the plugin totally and reinstall)

**Comment by haoming-li-ling** [comment]
The problem with the new version now is that the rule you provided does not even work. In fact, the default quotes map for tex also doesn't work.

**Comment by altermo** [comment]
Fixed; the problem was that treesitter uses latex and not tex as languagetree:lang().
So replace `{ft={'text'}}` with {ft={'text','latex'}}`

**Comment by haoming-li-ling** [comment]
I commented out the double quotes rule for tex from internal pairs, and tried to add this rule:    
```lua
{ "`", "'", fly = true, ft = { "tex", "latex" } }
```
but this one doesn't work; why?

**Comment by altermo** [comment]
That's weird, cause it works with the minimal config:
```lua
vim.fn.system{'git','clone','--depth=1','https://github.com/altermo/ultimate-autopair.nvim',vim.fn.stdpath('data')..'/ultimate-autopair'}
vim.opt.runtimepath:append(vim.fn.stdpath('data')..'/ultimate-autopair')
require'ultimate-autopair'.setup{{'`',"'",fly=true,ft={'tex','latex'}}}
vim.cmd.setf'tex'
```

**Comment by haoming-li-ling** [comment]
I located the plugin causing the issue. It is actually vimtex. Whenever vimtex is enabled, the \` rule does not work. However, I already disabled the auto-expanding snippets from vimtex that start with \`, so I don't know why this is still happening. Working alongside vimtex would be ideal, since virtually everyone writing latex on vim uses it.

Additionally,
```lua
{ "`", "`", nft = { "tex", "latex" }, multiline = false }
```
and 
```lua
{ "`", "'", fly = true, ft = { "tex", "latex" } }
```
cannot coexist. The former breaks the backspace behavior of the latter, despite the filetype specifications.

**Comment by altermo** [comment]
For the vimtex, I need a config to be able to search for what causes what.
And for the backspace, in what way does it break?

**Comment by haoming-li-ling** [comment]
For the broken backspace, it deletes two \`s at once, without deleting any 's. So
```
``|'' --backspace--> |''
```

**Comment by altermo** [comment]
Fixed; the problem was that only a select cases of backspace(/newline) ran through the filter and the rest ignored it.

**Comment by haoming-li-ling** [comment]
Indeed fixed. Thanks!

Something more drastic I noticed with vimtex. It is not that the backtick rule doesn't work; it works, but it interprets the single quotes not on the current line as the ending character. And so, it does not insert the single quote on the same line. Then, when I delete the backtick, a single quote that is very far away from the backtick (on the lines below) gets deleted. I think the multiline behavior is erroneously enabled for this rule when vimtex is enabled.

**Comment by haoming-li-ling** [comment]
Ok, setting multiline to false explicitly fixes it. It is still puzzling; what is the default setting for multiline? Why vimtex enabled means multiline on, and vimtex disabled means multiline off, even though I didn't set the multiline option at all in the original rule? Is it perhaps the timing of the filtetype detection that is affected by vimtex, which in turn affects whether the explicit `multiline = false` option from the `nft = { "tex", "latex" }` backtick rule gets transferred to the `ft = { "tex", "latex" }` backtick rule?

**Comment by altermo** [comment]
The default for multiline is true.
Can you give a minimal config so that I can also research it?
